// sources for every wing and every lookup table.
// every entry in the db must have at least one cite here. app.js checks this and flags any wing without one.

// publishers, with what kind of source they are and how much to lean on them
const publishers = {
  "wikipedia": { kind: "encyclopedia", tier: "general", note: "open encyclopedia. good for overviews. check its own references for details." },
  "nasa glenn research center": { kind: "government science", tier: "expert", note: "the beginner's guide to aeronautics from a nasa research center." }
};

// build a wikipedia source from an article title. titles are kept lowercase here;
// wikipedia ignores case on the first letter and redirects the rest where needed
const wiki = title => ({
  publisher: "wikipedia",
  title,
  url: "https://en.wikipedia.org/wiki/" + encodeURIComponent(title.replace(/ /g, "_"))
});
const nasa = (page, title) => ({
  publisher: "nasa glenn research center",
  title,
  url: "https://www.grc.nasa.gov/www/k-12/airplane/" + page
});

// every source, keyed by a short name
const sources = {
  "nasa-guide": nasa("index.html", "beginner's guide to aeronautics"),
  "nasa-geometry": nasa("geom.html", "wing geometry definitions"),
  "nasa-reynolds": nasa("reynolds.html", "reynolds number"),
  "wing": wiki("wing"),
  "flight": wiki("flight"),
  "lift": wiki("lift (force)"),
  "reynolds": wiki("reynolds number"),
  "materials": wiki("materials science"),
  "aircraft": wiki("aircraft"),
  "convergent": wiki("convergent evolution"),
  "seed-dispersal": wiki("seed dispersal"),
  "insect-flight": wiki("insect flight"),
  "insect-wing": wiki("insect wing"),
  "feather": wiki("feather"),
  "wing-configuration": wiki("wing configuration"),
  "swept-wing": wiki("swept wing"),
  "forward-swept-wing": wiki("forward-swept wing"),
  "delta-wing": wiki("delta wing"),
  "variable-sweep-wing": wiki("variable-sweep wing"),
  "oblique-wing": wiki("oblique wing"),
  "flying-wing": wiki("flying wing"),
  "blended-wing-body": wiki("blended wing body"),
  "aspect-ratio": wiki("aspect ratio (aeronautics)"),
  "closed-wing": wiki("closed wing"),
  "elliptical-wing": wiki("elliptical wing"),
  "monoplane": wiki("monoplane"),
  "gull-wing": wiki("gull wing"),
  "biplane": wiki("biplane"),
  "triplane": wiki("triplane"),
  "tandem-wing": wiki("tandem wing"),
  "wingtip-device": wiki("wingtip device"),
  "flap": wiki("flap (aeronautics)"),
  "slat": wiki("leading-edge slat"),
  "aileron": wiki("aileron"),
  "spoiler": wiki("spoiler (aeronautics)"),
  "canard": wiki("canard (aeronautics)"),
  "bird-flight": wiki("bird flight"),
  "bat-flight": wiki("bat flight"),
  "bat": wiki("bat"),
  "pterosaur": wiki("pterosaur"),
  "dragonfly": wiki("dragonfly"),
  "butterfly": wiki("butterfly"),
  "elytron": wiki("elytron"),
  "halteres": wiki("halteres"),
  "bee": wiki("bee"),
  "thrips": wiki("thrips"),
  "flying-squirrel": wiki("flying squirrel"),
  "sugar-glider": wiki("sugar glider"),
  "colugo": wiki("colugo"),
  "draco": wiki("draco (lizard)"),
  "flying-frog": wiki("flying frog"),
  "chrysopelea": wiki("chrysopelea"),
  "flying-fish": wiki("flying fish"),
  "penguin": wiki("penguin"),
  "manta-ray": wiki("manta ray"),
  "sea-turtle": wiki("sea turtle"),
  "sea-angel": wiki("sea angel"),
  "flightless-bird": wiki("flightless bird"),
  "kiwi": wiki("kiwi (bird)"),
  "hummingbird": wiki("hummingbird"),
  "flight-feather": wiki("flight feather"),
  "alula": wiki("alula"),
  "helicopter-rotor": wiki("helicopter rotor"),
  "autogyro": wiki("autogyro"),
  "propeller": wiki("propeller (aeronautics)"),
  "wind-turbine": wiki("wind turbine"),
  "samara": wiki("samara (fruit)"),
  "hang-gliding": wiki("hang gliding"),
  "paragliding": wiki("paragliding"),
  "wingsuit": wiki("wingsuit flying"),
  "kite": wiki("kite"),
  "glider": wiki("glider (sailplane)"),
  "downforce": wiki("downforce"),
  "sail": wiki("sail"),
  "keel": wiki("keel"),
  "hydrofoil": wiki("hydrofoil"),
  "ground-effect": wiki("ground-effect vehicle"),
  "fin": wiki("fin"),
  "ornithopter": wiki("ornithopter"),
  "robobee": wiki("robobee"),
  "uav": wiki("unmanned aerial vehicle"),
  "dragon": wiki("dragon"),
  "angel": wiki("angel"),
  "fairy": wiki("fairy"),
  "icarus": wiki("icarus"),
  "pegasus": wiki("pegasus"),
  "talaria": wiki("talaria"),
  "aviator-badge": wiki("aviator badge"),
  "caduceus": wiki("caduceus"),
  "winged-sun": wiki("winged sun"),
  "alsomitra": wiki("alsomitra macrocarpa"),
  "dipterocarpaceae": wiki("dipterocarpaceae"),
  "pine": wiki("pine"),
  "elm": wiki("elm"),
  "ailanthus": wiki("ailanthus altissima"),
  "taraxacum": wiki("taraxacum"),
  "asclepias": wiki("asclepias"),
  "space-shuttle-orbiter": wiki("space shuttle orbiter"),
  "lifting-body": wiki("lifting body"),
  "waverider": wiki("waverider"),
  "ingenuity": wiki("ingenuity (helicopter)"),
  "solar-sail": wiki("solar sail"),
  "solar-aircraft": wiki("solar-powered aircraft"),
  "nut": wiki("nut (hardware)"),
  "side-mirror": wiki("side-view mirror"),
  "wing-chair": wiki("wing chair"),
  "fender": wiki("fender (vehicle)"),
  "theatre": wiki("parts of a theatre"),
  "wing-building": wiki("wing (building)"),
  "buffalo-wing": wiki("buffalo wing"),
  "winger": wiki("winger (sports)"),
  "left-wing": wiki("left-wing politics"),
  "military-wing": wiki("wing (military unit)"),
  "archaeopteryx": wiki("archaeopteryx"),
  "microraptor": wiki("microraptor"),
  "yi": wiki("yi (dinosaur)"),
  "meganeura": wiki("meganeura"),
  "coelurosauravus": wiki("coelurosauravus")
};

// which sources back each wing: [source key, what it supports]
// what it supports is one of: overview, shape, parts, biology, history, physics, name
const cites = {
  "straight": [["wing-configuration", "shape"], ["nasa-geometry", "shape"]],
  "tapered": [["wing-configuration", "shape"], ["nasa-geometry", "shape"]],
  "elliptical": [["elliptical-wing", "overview"]],
  "swept": [["swept-wing", "overview"], ["wing-configuration", "shape"]],
  "forward-swept": [["forward-swept-wing", "overview"]],
  "delta": [["delta-wing", "overview"]],
  "cropped-delta": [["delta-wing", "shape"]],
  "ogive": [["delta-wing", "shape"]],
  "variable-sweep": [["variable-sweep-wing", "overview"]],
  "oblique": [["oblique-wing", "overview"]],
  "flying-wing": [["flying-wing", "overview"]],
  "blended": [["blended-wing-body", "overview"]],
  "high-aspect": [["aspect-ratio", "physics"], ["nasa-geometry", "shape"]],
  "annular": [["closed-wing", "overview"]],
  "low-wing": [["monoplane", "shape"], ["wing-configuration", "shape"]],
  "mid-wing": [["monoplane", "shape"], ["wing-configuration", "shape"]],
  "high-wing": [["monoplane", "shape"], ["wing-configuration", "shape"]],
  "parasol": [["monoplane", "shape"]],
  "gull": [["gull-wing", "overview"]],
  "inverted-gull": [["gull-wing", "shape"]],
  "monoplane": [["monoplane", "overview"]],
  "biplane": [["biplane", "overview"]],
  "triplane": [["triplane", "overview"]],
  "tandem": [["tandem-wing", "overview"]],
  "box": [["closed-wing", "overview"]],
  "winglet": [["wingtip-device", "overview"]],
  "flap": [["flap", "parts"]],
  "slat": [["slat", "parts"]],
  "aileron": [["aileron", "parts"]],
  "spoiler": [["spoiler", "parts"]],
  "canard": [["canard", "overview"]],
  "bird": [["bird-flight", "biology"], ["feather", "parts"]],
  "bat": [["bat-flight", "biology"], ["bat", "overview"]],
  "pterosaur": [["pterosaur", "biology"]],
  "dragonfly": [["dragonfly", "biology"], ["insect-flight", "physics"]],
  "butterfly": [["butterfly", "biology"], ["insect-wing", "parts"]],
  "beetle": [["elytron", "parts"]],
  "fly": [["halteres", "parts"]],
  "bee": [["bee", "biology"], ["insect-flight", "physics"]],
  "thrips": [["thrips", "biology"], ["insect-flight", "physics"]],
  "flying-squirrel": [["flying-squirrel", "biology"]],
  "sugar-glider": [["sugar-glider", "biology"]],
  "colugo": [["colugo", "biology"]],
  "draco": [["draco", "biology"]],
  "flying-frog": [["flying-frog", "biology"]],
  "flying-snake": [["chrysopelea", "biology"]],
  "flying-fish": [["flying-fish", "biology"]],
  "penguin": [["penguin", "biology"]],
  "manta": [["manta-ray", "biology"]],
  "sea-turtle": [["sea-turtle", "biology"]],
  "sea-angel": [["sea-angel", "biology"]],
  "ostrich": [["flightless-bird", "biology"]],
  "kiwi": [["kiwi", "biology"], ["flightless-bird", "biology"]],
  "elliptical-bird": [["bird-flight", "shape"]],
  "high-speed-bird": [["bird-flight", "shape"]],
  "active-soaring": [["bird-flight", "shape"]],
  "passive-soaring": [["bird-flight", "shape"]],
  "hovering": [["hummingbird", "biology"], ["bird-flight", "shape"]],
  "primaries": [["flight-feather", "parts"]],
  "secondaries": [["flight-feather", "parts"]],
  "alula": [["alula", "parts"]],
  "coverts": [["flight-feather", "parts"], ["feather", "parts"]],
  "rotor": [["helicopter-rotor", "overview"]],
  "autogyro": [["autogyro", "overview"]],
  "propeller": [["propeller", "overview"]],
  "turbine": [["wind-turbine", "overview"]],
  "maple-seed": [["samara", "biology"], ["seed-dispersal", "biology"]],
  "hang-glider": [["hang-gliding", "overview"]],
  "paraglider": [["paragliding", "overview"]],
  "wingsuit": [["wingsuit", "overview"]],
  "kite": [["kite", "overview"]],
  "sailplane": [["glider", "overview"], ["aspect-ratio", "physics"]],
  "race-wing": [["downforce", "physics"]],
  "sail": [["sail", "overview"]],
  "keel": [["keel", "overview"]],
  "hydrofoil": [["hydrofoil", "overview"]],
  "ekranoplan": [["ground-effect", "overview"]],
  "missile-fin": [["fin", "overview"]],
  "ornithopter": [["ornithopter", "overview"]],
  "robobee": [["robobee", "overview"]],
  "fixed-drone": [["uav", "overview"]],
  "dragon": [["dragon", "history"]],
  "angel": [["angel", "history"]],
  "fairy": [["fairy", "history"]],
  "icarus": [["icarus", "history"]],
  "pegasus": [["pegasus", "history"]],
  "hermes": [["talaria", "history"]],
  "pilot-wings": [["aviator-badge", "overview"]],
  "caduceus": [["caduceus", "history"]],
  "winged-sun": [["winged-sun", "history"]],
  "zanonia": [["alsomitra", "biology"], ["seed-dispersal", "biology"]],
  "dipterocarp": [["dipterocarpaceae", "biology"], ["seed-dispersal", "biology"]],
  "pine-seed": [["pine", "biology"], ["seed-dispersal", "biology"]],
  "elm-seed": [["elm", "biology"], ["samara", "biology"]],
  "tree-of-heaven": [["ailanthus", "biology"], ["samara", "biology"]],
  "dandelion": [["taraxacum", "biology"], ["seed-dispersal", "biology"]],
  "milkweed": [["asclepias", "biology"], ["seed-dispersal", "biology"]],
  "shuttle": [["space-shuttle-orbiter", "overview"]],
  "lifting-body": [["lifting-body", "overview"]],
  "waverider": [["waverider", "overview"]],
  "mars-rotor": [["ingenuity", "overview"]],
  "solar-sail": [["solar-sail", "overview"]],
  "solar-plane": [["solar-aircraft", "overview"]],
  "wing-nut": [["nut", "name"]],
  "wing-mirror": [["side-mirror", "name"]],
  "wingback": [["wing-chair", "name"]],
  "car-fender": [["fender", "name"]],
  "stage-wing": [["theatre", "name"]],
  "building-wing": [["wing-building", "name"]],
  "chicken-wing": [["buffalo-wing", "name"]],
  "winger": [["winger", "name"]],
  "political-wing": [["left-wing", "name"]],
  "air-force-wing": [["military-wing", "name"]],
  "archaeopteryx": [["archaeopteryx", "biology"]],
  "microraptor": [["microraptor", "biology"]],
  "yi-qi": [["yi", "biology"]],
  "meganeura": [["meganeura", "biology"]],
  "coelurosauravus": [["coelurosauravus", "biology"]]
};

// sources for the shared tables, shown on the sources page
const tableCites = {
  "materials": ["materials"],
  "flight modes": ["flight", "nasa-guide"],
  "scales (size, speed, aspect)": ["aspect-ratio", "nasa-geometry"],
  "flow numbers": ["reynolds", "nasa-reynolds"],
  "links (evolved like)": ["convergent"],
  "links (inspired, same idea)": ["wing", "aircraft"],
  "glossary": ["lift", "nasa-guide"],
  "seed wings": ["seed-dispersal"]
};
